spring:
  profiles:
    group:
      "local": "localDB, common"
      "server": "serverDB, common"

    default: "local" # active profile

---
spring:
  config:
    activate:
      on-profile: "localDB"

  datasource:
    url: jdbc:mariadb://localhost:3306/onelog
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1111

---
spring:
  config:
    activate:
      on-profile: "serverDB"

  datasource:
    url: jdbc:mariadb://yay.craceskswxlk.ap-northeast-2.rds.amazonaws.com:3306/yay
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 09420942

---
spring:
  config:
    activate:
      on-profile: "common"

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace # show parameter binding
      SQL: DEBUG


chatgpt:
  api-key: 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


